--
-- PostgreSQL database dump
--

\restrict 15PyrJYYF4lpvLwxrOeDdDnytGdfOcA6KQHitWzOOE9FfLV4QLUUJJQih3Fq7bJ

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.payments DROP CONSTRAINT IF EXISTS payments_appointment_id_fkey;
ALTER TABLE IF EXISTS ONLY public.patients DROP CONSTRAINT IF EXISTS patients_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.medical_records DROP CONSTRAINT IF EXISTS medical_records_patient_id_fkey;
ALTER TABLE IF EXISTS ONLY public.medical_records DROP CONSTRAINT IF EXISTS medical_records_doctor_id_fkey;
ALTER TABLE IF EXISTS ONLY public.medical_records DROP CONSTRAINT IF EXISTS medical_records_appointment_id_fkey;
ALTER TABLE IF EXISTS ONLY public.doctors DROP CONSTRAINT IF EXISTS doctors_user_id_fkey;
ALTER TABLE IF EXISTS ONLY public.doctor_schedules DROP CONSTRAINT IF EXISTS doctor_schedules_doctor_id_fkey;
ALTER TABLE IF EXISTS ONLY public.appointments DROP CONSTRAINT IF EXISTS appointments_schedule_id_fkey;
ALTER TABLE IF EXISTS ONLY public.appointments DROP CONSTRAINT IF EXISTS appointments_patient_id_fkey;
ALTER TABLE IF EXISTS ONLY public.appointments DROP CONSTRAINT IF EXISTS appointments_doctor_id_fkey;
ALTER TABLE IF EXISTS ONLY public.admins DROP CONSTRAINT IF EXISTS admins_user_id_fkey;
DROP INDEX IF EXISTS public.uq_appointments_schedule_id;
DROP INDEX IF EXISTS public.idx_payments_status;
DROP INDEX IF EXISTS public.idx_medical_records_patient_id;
DROP INDEX IF EXISTS public.idx_doctor_schedules_doctor_id;
DROP INDEX IF EXISTS public.idx_appointments_patient_id;
DROP INDEX IF EXISTS public.idx_appointments_doctor_id;
DROP INDEX IF EXISTS public.flyway_schema_history_s_idx;
ALTER TABLE IF EXISTS ONLY public.payments DROP CONSTRAINT IF EXISTS payments_pkey;
ALTER TABLE IF EXISTS ONLY public.payments DROP CONSTRAINT IF EXISTS payments_appointment_id_key;
ALTER TABLE IF EXISTS ONLY public.patients DROP CONSTRAINT IF EXISTS patients_pkey;
ALTER TABLE IF EXISTS ONLY public.medical_records DROP CONSTRAINT IF EXISTS medical_records_pkey;
ALTER TABLE IF EXISTS ONLY public.medical_records DROP CONSTRAINT IF EXISTS medical_records_appointment_id_key;
ALTER TABLE IF EXISTS ONLY public.flyway_schema_history DROP CONSTRAINT IF EXISTS flyway_schema_history_pk;
ALTER TABLE IF EXISTS ONLY public.doctors DROP CONSTRAINT IF EXISTS doctors_pkey;
ALTER TABLE IF EXISTS ONLY public.doctors DROP CONSTRAINT IF EXISTS doctors_license_number_key;
ALTER TABLE IF EXISTS ONLY public.doctor_schedules DROP CONSTRAINT IF EXISTS doctor_schedules_pkey;
ALTER TABLE IF EXISTS ONLY public.appointments DROP CONSTRAINT IF EXISTS appointments_pkey;
ALTER TABLE IF EXISTS ONLY public.app_users DROP CONSTRAINT IF EXISTS app_users_pkey;
ALTER TABLE IF EXISTS ONLY public.app_users DROP CONSTRAINT IF EXISTS app_users_email_key;
ALTER TABLE IF EXISTS ONLY public.admins DROP CONSTRAINT IF EXISTS admins_pkey;
DROP TABLE IF EXISTS public.payments;
DROP TABLE IF EXISTS public.patients;
DROP TABLE IF EXISTS public.medical_records;
DROP TABLE IF EXISTS public.flyway_schema_history;
DROP TABLE IF EXISTS public.doctors;
DROP TABLE IF EXISTS public.doctor_schedules;
DROP TABLE IF EXISTS public.appointments;
DROP TABLE IF EXISTS public.app_users;
DROP TABLE IF EXISTS public.admins;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admins (
    user_id bigint NOT NULL
);


--
-- Name: app_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.app_users (
    id bigint NOT NULL,
    role character varying(32) NOT NULL,
    full_name character varying(120) NOT NULL,
    email character varying(160) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: app_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appointments (
    id bigint NOT NULL,
    patient_id bigint NOT NULL,
    doctor_id bigint NOT NULL,
    schedule_id bigint,
    status character varying(24) NOT NULL,
    booked_at timestamp with time zone NOT NULL,
    complaint text,
    cancelled_reason character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: appointments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appointments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctor_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctor_schedules (
    id bigint NOT NULL,
    doctor_id bigint NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    ends_at timestamp with time zone NOT NULL,
    room character varying(40),
    status character varying(24) NOT NULL,
    notes character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: doctor_schedules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.doctor_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doctor_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.doctors (
    user_id bigint NOT NULL,
    specialization character varying(120) NOT NULL,
    license_number character varying(64) NOT NULL
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: medical_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medical_records (
    id bigint NOT NULL,
    appointment_id bigint NOT NULL,
    patient_id bigint NOT NULL,
    doctor_id bigint NOT NULL,
    symptoms text,
    diagnosis text NOT NULL,
    treatment_notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: medical_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.medical_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medical_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patients (
    user_id bigint NOT NULL,
    phone_number character varying(32) NOT NULL,
    date_of_birth date
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    appointment_id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    status character varying(24) NOT NULL,
    method_type character varying(24) NOT NULL,
    reference_number character varying(100),
    paid_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: admins; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.admins (user_id) FROM stdin;
1
\.


--
-- Data for Name: app_users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.app_users (id, role, full_name, email, password_hash, created_at, updated_at) FROM stdin;
1	ADMIN	admin	admin	$2a$10$2mMdNjaM6Gzr33UGKrc38eFx6jiFfwzKlSNrnuCFE52FCsFyGTL3m	2026-05-17 19:25:11.648127+07	2026-05-17 19:25:11.648127+07
8	PATIENT	patient zero	patient@patient.com	$2a$10$HUqMR3jRKHo/YsZ4W6L/5eTRENhHwBbqepSCnXSBTeuLLT87m3za2	2026-05-17 22:56:52.027665+07	2026-05-17 22:56:52.027665+07
11	PATIENT	patient one	patientone@patient.com	$2a$10$cxANynhc2kmvc6dtDa9DKeTZhBINX1Ok8yg0Ts59j/Ae50qD.KQZ.	2026-05-18 23:56:34.783299+07	2026-05-18 23:56:44.439081+07
13	PATIENT	lllll	email@gmail.com	$2a$10$PB1OM94K5zppGQbu1ml7N.DrYmn0AaKXfVnXh9cMe7fAYmRmAD6OK	2026-05-19 23:03:18.41381+07	2026-05-19 23:03:18.41381+07
14	PATIENT	akuakuaku	akju@aku.com	$2a$10$2LX3JfWbSjiCsEdI9o3/se2KxrENqQik4R7aj.SdEW0Zvh7dkffZi	2026-05-19 23:10:18.173372+07	2026-05-19 23:10:18.173372+07
10	DOCTOR	Dokter 2	dokter2@dokter.com	$2a$10$Vb4FYVOAGAMGmHYRtv8pTO3E6NO9gqf4azSDyDDilPAuX.dTDo.de	2026-05-18 21:13:26.50773+07	2026-05-24 17:59:18.592336+07
12	DOCTOR	Dokter 3	dokter3@dokter.com	$2a$10$ovDnRgKlkVKdBc2gjdSMdelR2Jnzw1cA4aldISEorbaNocy7Ew47K	2026-05-19 23:03:01.629951+07	2026-05-24 17:59:29.487181+07
9	DOCTOR	Dokter 1	dokter1@dokter.com	$2a$10$8e2yS46Zl6yfEHvnNWkMO.KvYKCKzhM0L7C.wSX7FkO1mTx2v/cxG	2026-05-18 18:28:19.873789+07	2026-06-16 13:20:12.330251+07
15	DOCTOR	Dokter Tawon	tawon@tawon.com	$2a$10$mpuoDx0SMDW8242rIb3qMOLRV1If2zhNpJTZJex2FcCNOH607THSS	2026-06-16 17:16:46.977833+07	2026-06-16 17:16:46.977833+07
\.


--
-- Data for Name: appointments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.appointments (id, patient_id, doctor_id, schedule_id, status, booked_at, complaint, cancelled_reason, created_at, updated_at) FROM stdin;
1	8	9	1	SELESAI	2026-05-19 09:00:00+07	sakit hati	\N	2026-05-19 00:07:16.037881+07	2026-05-21 21:07:20.228078+07
5	14	10	5	SELESAI	2026-05-21 08:30:00+07	\N	\N	2026-05-19 23:21:26.113208+07	2026-05-21 21:07:23.109237+07
9	14	10	9	MENUNGGU	2026-05-22 08:30:00+07	\N	\N	2026-05-21 21:11:32.651407+07	2026-05-21 21:11:32.651407+07
10	13	12	10	SELESAI	2026-05-22 09:00:00+07	\N	\N	2026-05-21 21:28:02.162837+07	2026-05-21 21:38:18.099236+07
11	14	12	11	SELESAI	2026-05-22 11:30:00+07	\N	\N	2026-05-21 21:38:42.109292+07	2026-05-21 21:39:03.653555+07
14	8	9	14	SELESAI	2026-05-26 08:00:00+07	Sakit gigi dok	\N	2026-05-24 18:00:48.734045+07	2026-05-24 18:01:04.984526+07
13	8	10	15	SELESAI	2026-05-25 08:30:00+07	woyyy	\N	2026-05-24 17:56:46.713309+07	2026-06-15 19:39:24.103999+07
12	8	9	13	SELESAI	2026-05-25 07:30:00+07	sakit punggung	\N	2026-05-24 15:23:50.451844+07	2026-06-15 19:39:26.236447+07
16	11	9	19	DISETUJUI	2026-06-30 09:00:00+07	Sakit punggung	\N	2026-06-16 17:15:09.942359+07	2026-06-16 17:15:09.942359+07
\.


--
-- Data for Name: doctor_schedules; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.doctor_schedules (id, doctor_id, starts_at, ends_at, room, status, notes, created_at, updated_at) FROM stdin;
1	9	2026-05-19 09:00:00+07	2026-05-19 11:00:00+07	ix-10b	BOOKED	krn sakit hati lgsg suntik mati aja dok udh gbs dibantu itu	2026-05-19 00:07:16.025171+07	2026-05-19 00:07:16.025171+07
5	10	2026-05-21 08:30:00+07	2026-05-21 10:00:00+07	\N	BOOKED	\N	2026-05-19 23:21:26.112063+07	2026-05-19 23:21:26.112063+07
9	10	2026-05-22 08:30:00+07	2026-05-22 10:00:00+07	\N	BOOKED	\N	2026-05-21 21:11:32.650493+07	2026-05-21 21:11:32.650493+07
10	12	2026-05-22 09:00:00+07	2026-05-22 11:30:00+07	Something	BOOKED	Something	2026-05-21 21:28:02.161218+07	2026-05-21 21:28:02.161218+07
11	12	2026-05-22 11:30:00+07	2026-05-22 13:00:00+07	\N	BOOKED	\N	2026-05-21 21:38:42.107449+07	2026-05-21 21:38:42.107449+07
12	9	2026-05-23 09:30:00+07	2026-05-23 11:00:00+07	\N	AVAILABLE	\N	2026-05-22 15:56:00.472421+07	2026-05-22 15:56:00.472421+07
13	9	2026-05-25 07:30:00+07	2026-05-25 09:30:00+07	RP-0102	BOOKED	\N	2026-05-24 14:42:06.733148+07	2026-05-24 15:23:50.470765+07
16	12	2026-05-25 08:30:00+07	2026-05-25 10:30:00+07	\N	AVAILABLE	\N	2026-05-24 15:24:49.442103+07	2026-05-24 15:24:49.442103+07
15	10	2026-05-25 08:30:00+07	2026-05-25 10:30:00+07	\N	BOOKED	\N	2026-05-24 15:24:44.645668+07	2026-05-24 17:56:46.716644+07
14	9	2026-05-26 08:00:00+07	2026-05-26 09:30:00+07	RP-0103	BOOKED	\N	2026-05-24 15:24:33.119171+07	2026-05-24 18:00:48.735306+07
18	9	2026-06-22 09:00:00+07	2026-06-22 10:00:00+07	Ruangan 1	AVAILABLE	\N	2026-06-15 19:42:59.106967+07	2026-06-15 19:42:59.106967+07
19	9	2026-06-30 09:00:00+07	2026-06-30 09:30:00+07	TULT 0807	BOOKED	Sakit punggung???	2026-06-16 17:15:09.930716+07	2026-06-16 17:15:09.930716+07
\.


--
-- Data for Name: doctors; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.doctors (user_id, specialization, license_number) FROM stdin;
12	Ortho	35123532
9	Penyakit Dalam	2352325
10	Kardiologi	2352342
15	Gigi	LV-2224151
\.


--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) FROM stdin;
1	1	init schema	SQL	V1__init_schema.sql	274231331	postgres	2026-05-17 19:25:11.596659	31	t
2	2	seed admin user	SQL	V2__seed_admin_user.sql	1420184588	postgres	2026-05-17 19:25:11.642861	2	t
\.


--
-- Data for Name: medical_records; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.medical_records (id, appointment_id, patient_id, doctor_id, symptoms, diagnosis, treatment_notes, created_at, updated_at) FROM stdin;
1	11	14	12	Sakit bro	sakit deh pokoknya	idk	2026-05-24 17:36:15.727451+07	2026-05-24 17:36:15.727451+07
2	14	8	9	Boong ternyata	ga sakit	ga diapa apain	2026-05-24 18:01:20.298929+07	2026-05-24 18:01:20.298929+07
3	12	8	9	Sakit Punggung nya sudah sembuh yaaa	sakit punggung	di obatin	2026-06-16 17:15:35.326608+07	2026-06-16 17:15:35.326608+07
\.


--
-- Data for Name: patients; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.patients (user_id, phone_number, date_of_birth) FROM stdin;
8	string	2026-05-17
11	0822534232	2026-05-19
13	52323425623	2026-05-21
14	305235235	\N
\.


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.payments (id, appointment_id, amount, status, method_type, reference_number, paid_at, created_at, updated_at) FROM stdin;
2	1	250000.00	LUNAS	CASH	\N	2026-05-24 19:01:08.696613+07	2026-05-24 19:00:59.646521+07	2026-05-24 19:01:08.698044+07
1	5	2500000.00	LUNAS	CASH	blablbla	2026-06-15 19:40:09.709624+07	2026-05-24 18:54:30.168179+07	2026-06-15 19:40:09.711249+07
\.


--
-- Name: app_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.app_users_id_seq', 15, true);


--
-- Name: appointments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.appointments_id_seq', 16, true);


--
-- Name: doctor_schedules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.doctor_schedules_id_seq', 19, true);


--
-- Name: medical_records_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.medical_records_id_seq', 3, true);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.payments_id_seq', 2, true);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (user_id);


--
-- Name: app_users app_users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_email_key UNIQUE (email);


--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);


--
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);


--
-- Name: doctor_schedules doctor_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor_schedules
    ADD CONSTRAINT doctor_schedules_pkey PRIMARY KEY (id);


--
-- Name: doctors doctors_license_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_license_number_key UNIQUE (license_number);


--
-- Name: doctors doctors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_pkey PRIMARY KEY (user_id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: medical_records medical_records_appointment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT medical_records_appointment_id_key UNIQUE (appointment_id);


--
-- Name: medical_records medical_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT medical_records_pkey PRIMARY KEY (id);


--
-- Name: patients patients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patients_pkey PRIMARY KEY (user_id);


--
-- Name: payments payments_appointment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_appointment_id_key UNIQUE (appointment_id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_appointments_doctor_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_appointments_doctor_id ON public.appointments USING btree (doctor_id);


--
-- Name: idx_appointments_patient_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_appointments_patient_id ON public.appointments USING btree (patient_id);


--
-- Name: idx_doctor_schedules_doctor_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_doctor_schedules_doctor_id ON public.doctor_schedules USING btree (doctor_id);


--
-- Name: idx_medical_records_patient_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_medical_records_patient_id ON public.medical_records USING btree (patient_id);


--
-- Name: idx_payments_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payments_status ON public.payments USING btree (status);


--
-- Name: uq_appointments_schedule_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_appointments_schedule_id ON public.appointments USING btree (schedule_id) WHERE (schedule_id IS NOT NULL);


--
-- Name: admins admins_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id) ON DELETE CASCADE;


--
-- Name: appointments appointments_doctor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(user_id);


--
-- Name: appointments appointments_patient_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(user_id);


--
-- Name: appointments appointments_schedule_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.doctor_schedules(id);


--
-- Name: doctor_schedules doctor_schedules_doctor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctor_schedules
    ADD CONSTRAINT doctor_schedules_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(user_id);


--
-- Name: doctors doctors_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.doctors
    ADD CONSTRAINT doctors_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id) ON DELETE CASCADE;


--
-- Name: medical_records medical_records_appointment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT medical_records_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id);


--
-- Name: medical_records medical_records_doctor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT medical_records_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(user_id);


--
-- Name: medical_records medical_records_patient_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medical_records
    ADD CONSTRAINT medical_records_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(user_id);


--
-- Name: patients patients_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patients_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id) ON DELETE CASCADE;


--
-- Name: payments payments_appointment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 15PyrJYYF4lpvLwxrOeDdDnytGdfOcA6KQHitWzOOE9FfLV4QLUUJJQih3Fq7bJ

