create table app_users (
    id bigint generated by default as identity primary key,
    role varchar(32) not null,
    full_name varchar(120) not null,
    email varchar(160) not null unique,
    password_hash varchar(255) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table admins (
    user_id bigint primary key references app_users (id) on delete cascade
);

create table doctors (
    user_id bigint primary key references app_users (id) on delete cascade,
    specialization varchar(120) not null,
    license_number varchar(64) not null unique
);

create table patients (
    user_id bigint primary key references app_users (id) on delete cascade,
    phone_number varchar(32) not null,
    date_of_birth date
);

create table doctor_schedules (
    id bigint generated by default as identity primary key,
    doctor_id bigint not null references doctors (user_id),
    starts_at timestamp with time zone not null,
    ends_at timestamp with time zone not null,
    room varchar(40),
    status varchar(24) not null,
    notes varchar(255),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table appointments (
    id bigint generated by default as identity primary key,
    patient_id bigint not null references patients (user_id),
    doctor_id bigint not null references doctors (user_id),
    schedule_id bigint references doctor_schedules (id),
    status varchar(24) not null,
    booked_at timestamp with time zone not null,
    complaint text,
    cancelled_reason varchar(255),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create unique index uq_appointments_schedule_id
    on appointments (schedule_id)
    where schedule_id is not null;

create table medical_records (
    id bigint generated by default as identity primary key,
    appointment_id bigint not null unique references appointments (id),
    patient_id bigint not null references patients (user_id),
    doctor_id bigint not null references doctors (user_id),
    symptoms text,
    diagnosis text not null,
    treatment_notes text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table payments (
    id bigint generated by default as identity primary key,
    appointment_id bigint not null unique references appointments (id),
    amount numeric(12, 2) not null,
    status varchar(24) not null,
    method_type varchar(24) not null,
    reference_number varchar(100),
    paid_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_doctor_schedules_doctor_id on doctor_schedules (doctor_id);
create index idx_appointments_doctor_id on appointments (doctor_id);
create index idx_appointments_patient_id on appointments (patient_id);
create index idx_medical_records_patient_id on medical_records (patient_id);
create index idx_payments_status on payments (status);
